spring:
  cloud:
    nacos:
      serverAddr: 127.0.0.1:8848 #如果用的云上托管版本，输入可访问的Nacos Server地址即可
      discovery:
        server-addr: ${spring.cloud.nacos.server-addr}
  config:
    import:
      - nacos:nacos-config-demo?refreshEnabled=true
  application:
    name: nacos-config-demo
server:
  port: 8081
